blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/px4n/hugo-syndicate#readme
    about: Check the README for configuration and usage information
  - name: Security Issue(s)
    url: https://github.com/px4n/hugo-syndicate/security/advisories/new
    about: Please report security vulnerabilities privately
